{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gcrcg.fullname" }}
  annotations:
    {{- toYaml .Values.secret.annotations | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.secret.credentials | b64enc }}
{{- end }}
