apiVersion: v2
name: gcrgc
version: 0.1.10
description: A Helm chart for the GCR Garbage Collector
type: application
sources:
  - https://github.com/graillus/helm-charts
maintainers:
  - name: Robin Graillon
    email: robin.graillon@gmail.com
    url: https://github.com/graillus
appVersion: 0.4.0
